spring.application.name=mysite
#database
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:~/local;IFEXISTS=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

#jpa
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.show_sql=true
#ddl-auto=none : ìí°í°ê° ë³ê²½ëëë¼ë DBë¥¼ ë³ê²½íì§ ìëë¤.
#ddl-auto=update : ìí°í°ì ë³ê²½ë ë¶ë¶ë§ DBì ì ì¥íë¤.
#ddl-auto=create : ì¤íë§ë¶í¸ ìë²ë¥¼ ììí  ë tableì ì ë¶ ì­ì  í ë¤ì ìì±
#ddl-auto=validate : íì´ë¸ì ê²ì¬ë§ íë¤.


#파일 업로드 설정
spring.servlet.multipart.enabled=true
spring.servlet.multipart.location=C:/upload
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=30MB